// Sample data for development - will be replaced with API calls

import { Story, NewsArticle, Event } from '@/types';

export const sampleStories: Story[] = [
  {
    id: '1',
    title: 'Finding Light in the Darkness',
    slug: 'finding-light-in-darkness',
    name: 'Maria Rodriguez',
    age: 32,
    type: 'video',
    category: 'Recovery',
    excerpt: 'After 10 years of struggling with opioid addiction, Maria found hope through community support and treatment. Today, she\'s 3 years sober and helps others on their recovery journey.',
    content: 'Full story content here...',
    image: '/images/stories/maria.jpg',
    videoUrl: 'https://example.com/video/maria',
    duration: '8:24',
    featured: true,
    publishedAt: new Date('2025-09-15'),
    createdAt: new Date('2025-09-10'),
    updatedAt: new Date('2025-09-15'),
  },
  {
    id: '2',
    title: 'A Family\'s Journey to Healing',
    slug: 'family-journey-to-healing',
    name: 'James Chen',
    age: 28,
    type: 'audio',
    category: 'Family Support',
    excerpt: 'James shares his family\'s experience supporting his brother through addiction recovery, highlighting the importance of compassion and understanding.',
    content: 'Full story content here...',
    image: '/images/stories/james.jpg',
    audioUrl: 'https://example.com/audio/james',
    duration: '12:45',
    publishedAt: new Date('2025-09-20'),
    createdAt: new Date('2025-09-18'),
    updatedAt: new Date('2025-09-20'),
  },
];

export const sampleNews: NewsArticle[] = [
  {
    id: '1',
    title: 'New Study Shows Rising Addiction Rates Among Youth',
    slug: 'rising-addiction-rates-youth',
    excerpt: 'Recent research reveals a 23% increase in substance abuse among teenagers, highlighting the urgent need for prevention and early intervention programs.',
    content: 'Full article content...',
    category: 'Research',
    author: 'Dr. Sarah Johnson',
    image: '/images/news/youth-study.jpg',
    readTime: '5 min read',
    featured: true,
    publishedAt: new Date('2025-10-08'),
    createdAt: new Date('2025-10-07'),
    updatedAt: new Date('2025-10-08'),
    tags: ['research', 'youth', 'prevention'],
  },
  {
    id: '2',
    title: 'Recovery Walk 2026 Registration Now Open',
    slug: 'recovery-walk-2026-registration',
    excerpt: 'Join thousands as we walk together to celebrate recovery and raise awareness.',
    content: 'Full article content...',
    category: 'Events',
    author: 'Community Team',
    image: '/images/news/recovery-walk.jpg',
    readTime: '3 min read',
    publishedAt: new Date('2025-10-05'),
    createdAt: new Date('2025-10-04'),
    updatedAt: new Date('2025-10-05'),
    tags: ['events', 'community', 'recovery'],
  },
];

export const sampleEvents: Event[] = [
  {
    id: '1',
    title: 'Recovery Walk 2026',
    slug: 'recovery-walk-2026',
    description: 'Join thousands of people in recovery, their families, and supporters for an inspiring day of unity, hope, and celebration.',
    type: 'Community Event',
    date: new Date('2026-06-15'),
    time: '9:00 AM',
    endTime: '2:00 PM',
    location: 'Central Park',
    address: 'Central Park, New York City, NY 10024',
    attendees: 2500,
    maxAttendees: 5000,
    image: '/images/events/recovery-walk.jpg',
    organizer: 'Secure the Future',
    contactEmail: 'events@securethefuture.org',
    contactPhone: '1-234-567-890',
    featured: true,
    registrationRequired: true,
    registrationUrl: 'https://example.com/register/recovery-walk-2026',
    createdAt: new Date('2025-09-01'),
    updatedAt: new Date('2025-10-05'),
    tags: ['recovery', 'community', 'awareness'],
  },
  {
    id: '2',
    title: 'Family Support Group Meeting',
    slug: 'family-support-group-oct',
    description: 'Monthly support group for families affected by addiction.',
    type: 'Support Group',
    date: new Date('2025-10-18'),
    time: '6:30 PM',
    endTime: '8:00 PM',
    location: 'Community Center',
    address: '456 Hope Street, Recovery City, RC 12345',
    attendees: 45,
    maxAttendees: 60,
    image: '/images/events/support-group.jpg',
    organizer: 'Secure the Future',
    contactEmail: 'support@securethefuture.org',
    featured: false,
    registrationRequired: false,
    createdAt: new Date('2025-09-15'),
    updatedAt: new Date('2025-09-15'),
    tags: ['support', 'family', 'monthly'],
  },
];
